name: My first workflow

on: workflow_dispatch

jobs:
  my-amazing-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The amazing job has started"
      - run: echo "this was triggered by a ${{ github.event_name }} event."
      - run: echo "this was run on ${{runner.os}}"
      - run: echo "started in ${{github.repository}} on ${{github.ref#refs/heads/}} branch"
      - run: echo "the amazing job is complete"
